#!/bin/bash

cd store1
go build
cp store1 /root/docker/store1/store
cd ..

cd store2
go build
cp store2 /root/docker/store2/store
cd ..

cd hash
go build
cp hash /root/docker/hash/
cd ..

cd entry
go build
cp entry /root/docker/entry/
cd ..
